name: laptop_harbor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  persistent_shopping_cart: ^0.0.7
  get_it: ^7.2.0
  injectable: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # add the generator to your dev_dependencies
  injectable_generator:
  # add build runner if not already added
  build_runner:


flutter:
  uses-material-design: true
