// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0VGpnVA5pue-8mP6Cp6WBbv-3WcFV4MI',
    appId: '1:854632199686:web:6bdf1df05372adc019b587',
    messagingSenderId: '854632199686',
    projectId: 'aptech-flutter-fire',
    authDomain: 'aptech-flutter-fire.firebaseapp.com',
    storageBucket: 'aptech-flutter-fire.appspot.com',
    measurementId: 'G-HSQ9XN587H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9p_a9EMfL7KvFSdTxQs75NDop5cYwuJU',
    appId: '1:854632199686:android:34db530ac0a0431719b587',
    messagingSenderId: '854632199686',
    projectId: 'aptech-flutter-fire',
    storageBucket: 'aptech-flutter-fire.appspot.com',
  );

}